# Generated by Django 2.2.4 on 2019-11-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoodies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=250)),
                ('productId', models.CharField(max_length=20)),
                ('productPrice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
